
include: package:flutter_lints/flutter.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
    public_member_api_docs: false
    prefer_relative_imports: true

analyzer:
  exclude: 
    - "**/*.g.dart"
    - "**/*.freezed.dart"

dart_code_metrics:
  extends:
    - package:dart_code_metrics_presets/recommended.yaml
  metrics-exclude:
    - test/**
  rules-exclude:
    - "test/**"
  rules:
    prefer-match-file-name: false
    # Remove later when cleaning up
    prefer-single-widget-per-file: false
    # End of remove later
    match-getter-setter-field-names: false
    prefer-dedicated-media-query-methods: false
    avoid-shadowing: false
    
    enum-constants-ordering: false
    
    avoid-unsafe-collection-methods: false
    
    prefer-prefixed-global-constants: false
    avoid-returning-widgets: false
    arguments-ordering:
      child-last: true
    avoid-nested-conditional-expressions:
        acceptable-level: 3
    member-ordering:
        order:
          - public-fields
          - private-fields
          - constructors
          - static-methods
          - private-methods
          - private-getters
          - private-setters
          - public-getters
          - public-setters
          - public-methods
          - overridden-public-methods
          - overridden-public-getters
          - build-method
    prefer-named-boolean-parameters:
      ignore-single: true