name: mix
description: A new Flutter package project.
version: 0.0.1-dev.1
homepage: https://github.com/leoafarias/mix

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.17.0
  freezed_annotation: ^0.14.2

dev_dependencies:
  build_runner: ^2.0.4
  effective_dart: ^1.3.2
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  test_cov_console: ^0.0.4

flutter:
