name: mix
description: An expressive way to effortlessly build design systems in Flutter.
version: 0.0.1-dev.2
homepage: https://github.com/leoafarias/mix

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.17.0
  freezed_annotation: ^0.14.2

dev_dependencies:
  build_runner: ^2.0.4
  freezed: ^0.14.2
  test_cov_console: ^0.0.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.3

flutter:
