name: demo
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mix:
    path: ../

  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.1
  hooks_riverpod: ^1.0.0
  functional_widget: ^0.9.1
  adaptive_navigation: ^0.0.5
  google_fonts: ^2.3.2
  desktop_window: ^0.4.0
  community_material_icon: ^5.9.55

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
