name: Changelog

on:
  workflow_dispatch:
    inputs:
      mix:
        type: string
        description: set specific version for mix
        default: ""
      mix_lint:
        type: string
        description: set specific version for mix_lint
        default: ""
      mix_annotations:
        type: string
        description: set specific version for mix_annotations
        default: ""
      mix_generator:
        type: string
        description: set specific version for mix_generator
        default: ""

jobs:
  version:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Flutter version
      shell: bash
      run: |
        echo "========= Flutter Version ========="
        flutter --version
        echo "==================================="
        
    - name: Setup Melos
      uses: bluefireteam/melos-action@v3


    - name: Configure Git User
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'

    - name: Run melos version

      run: |
        packages_with_versions=""

        if [ "${{ github.event.inputs.mix }}" != "" ]; then
          packages_with_versions="$packages_with_versions -V mix:${{ github.event.inputs.mix }}"
        fi
        if [ "${{ github.event.inputs.mix_lint }}" != "" ]; then
          packages_with_versions="$packages_with_versions -V mix_lint:${{ github.event.inputs.mix_lint }}"
        fi
        if [ "${{ github.event.inputs.mix_annotations }}" != "" ]; then
          packages_with_versions="$packages_with_versions -V mix_annotations:${{ github.event.inputs.mix_annotations }}"
        fi
        if [ "${{ github.event.inputs.mix_generator }}" != "" ]; then
          packages_with_versions="$packages_with_versions -V mix_generator:${{ github.event.inputs.mix_generator }}"
        fi

        melos version -y $packages_with_versions

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: version packages'
        title: 'chore: version packages'
        body: 'This PR was opened by the changelog GitHub Actions workflow'
        branch: 'create-pull-request/package-versions'
