name: Publish to pub.dev

on:
  workflow_dispatch:

jobs:
  test-mincompat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mix repo
        uses: actions/checkout@v2

      - name: Run Tests
        uses: ./.github/actions/test/
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          flutter-version: 'mincompat'

  test-stable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mix repo
        uses: actions/checkout@v2

      - name: Run Tests
        uses: ./.github/actions/test/
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: [test-mincompat, test-stable]
    environment: Production
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install FVM
        shell: bash
        run: |
          curl -fsSL https://fvm.app/install.sh | bash
          fvm use stable --force

      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}

      - name: Flutter version
        shell: bash
        run: flutter --version

      - name: Setup Melos
        uses: bluefireteam/melos-action@v3
        with:
          publish: true
      