name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests_mix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout mix repo
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout remix_ui repo
        uses: actions/checkout@v2
        with:
          repository: conceptadev/remix_ui
          path: remix

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - run: flutter --version

      - run: cd main && flutter pub get

      # - uses: axel-op/dart-package-analyzer@v3
      #   with:
      #     githubToken: ${{ secrets.GITHUB_TOKEN }}
      - run: cd main && flutter test

      - name: Analyze Flutter Project
        run: |
          cd remix
          if flutter analyze | grep -q 'undefined'; then
            echo "A file contains undefined symbols. Please add a deprecated annotation before you remove it."
            exit 1
          fi

      - name: Add Label to Issue
        if: failure()
        uses: actions/github-script@v7
        with:
         script: |
          github.rest.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['New Deprecation']
          })

        

  # remix_build:
  #   runs-on: ubuntu-latest
  #   needs: tests_mix

  #   steps:
  #     - uses: actions/checkout@v4
  #       with: 
  #         repository: 'conceptadev/remix_ui'

  #     - uses: subosito/flutter-action@v2
  #       with:
  #         channel: "stable"
  #     # - run: flutter --version
  #     # - run: flutter pub get

      
        
