name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests_mix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout mix repo
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout remix_ui repo
        uses: actions/checkout@v2
        with:
          repository: conceptadev/remix_ui
          path: remix

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - run: flutter --version
      - run: flutter pub get

      # - uses: axel-op/dart-package-analyzer@v3
      #   with:
      #     githubToken: ${{ secrets.GITHUB_TOKEN }}
      - run: flutter test

      - name: Verify if there are any undefined symbols
        uses: actions/github-script@v7
        with:
          script: |
            flutter analyze | grep 'undefined'
            if [ $? -eq 0 ]; then
              core.setFailed('A file contains undefined symbols. Please add a deprecated annotation before you remove it.')
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['New Deprecation']
              })
            else
            fi
        

  remix_build:
    runs-on: ubuntu-latest
    needs: tests_mix

    steps:
      - uses: actions/checkout@v4
        with: 
          repository: 'conceptadev/remix_ui'

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      # - run: flutter --version
      # - run: flutter pub get

      
        
