name: Test Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout mix repo
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - run: flutter pub get

      - uses: invertase/github-action-dart-analyzer@v1
        with:
          fatal-infos: false

      - name: Install DCM
        uses: CQLabs/setup-dcm@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run DCM
        run: dcm analyze lib --fatal-style --fatal-performance --fatal-warnings

      # - name: Run DCM
      #   uses: CQLabs/dcm-action@v1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     folders: lib
      #     pull_request_comment_on_fail: true
          
        
      - run: flutter test
        

  analyze_breaking_changes:
    runs-on: ubuntu-latest
    name: Analyze Breaking Changes

    needs: test
    steps:
      - name: Checkout mix repo
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout remix_ui repo
        uses: actions/checkout@v2
        with:
          repository: conceptadev/remix_ui
          path: remix

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Add most recent mix version to remix_ui
        run: |
          cd remix
          dart pub remove mix
          dart pub add 'mix:{"git":{"url":"https://github.com/conceptadev/mix","ref": ${{ github.head_ref  }}}}'
      - name: Verify if there are any undefined symbols
        id: undefined_symbols
        run: |
          cd remix
          if flutter analyze lib | grep -q 'undefined'; then
            echo "A file contains undefined symbols. Please add a deprecated annotation before you remove it."
            exit 1
          fi
      - name: Add Label to Issue
        uses: actions/github-script@v7
        if: ${{ failure() && steps.undefined_symbols.conclusion == 'failure' }}
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['New Deprecation']
            })
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Hello 😊, we have noticed a breaking change in our API. Please add the deprecated annotation before you remove it.'
            })


  analyze_behavior_changes:
    runs-on: ubuntu-latest
    name: Analyze Behavior Changes
    continue-on-error: true
    needs: analyze_breaking_changes
    if: ${{ needs.analyze_breaking_changes.result == 'success' }}
    steps:
      - name: Checkout mix repo
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout remix_ui repo
        uses: actions/checkout@v2
        with:
          repository: conceptadev/remix_ui
          path: remix

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

    
      - name: Add most recent mix version to remix_ui
        run: |
          cd remix
          dart pub remove mix
          dart pub add 'mix:{"git":{"url":"https://github.com/conceptadev/mix","ref":${{ github.head_ref  }}}}'

      - run: cd remix && flutter test
        id: remix_test

      - name: Add Label to Issue and Comment
        uses: actions/github-script@v7
        if: ${{ failure() && steps.remix_test.conclusion == 'failure' }}
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Behavior Change']
            })
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "We have noticed a change in Mix's behavior. Are you sure about this"
            })
